[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
plugin_core = { path = "../plugin_core" }
tokio = { version = "1", features = ["full"] }
clap = { version = "4.0", features = ["derive"] }
