[package]
name = "plugin_core"
version = "0.1.0"
edition = "2021"


[dependencies]
surrealdb = {version = "1.0.0", features = ["kv-indxdb"]}
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }

