name: Notify on Release

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Release Notes to Discord
        uses: SethCohen/github-releases-to-discord@v1.16.2
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          color: "2105893"  # Optional: Customize the embed color
          username: "Stack App Release"  # Optional: Customize the bot's username
          avatar_url: "https://e7.pngegg.com/pngimages/737/804/png-clipart-ultron-logo-marvel-comics-chitauri-hydra-ultron-face-fictional-characters.png"  # Optional: Customize the bot's avatar
          content: "@testers a new version of stack app has been released"  # Optional: Mention everyone in the channel
          footer_title: "Release Notes"
          footer_icon_url: "https://e7.pngegg.com/pngimages/737/804/png-clipart-ultron-logo-marvel-comics-chitauri-hydra-ultron-face-fictional-characters.png"
          footer_timestamp: true
          max_description: '4096'
          reduce_headings: true

  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install SendGrid Mail Package
        run: npm install 
        working-directory: ./scripts

      - name: Send Email with Release Notes
        run: node send_gmail.js
        working-directory: ./scripts
        env:
          #SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}
          RELEASE_NAME: ${{ github.event.release.name }}
          RELEASE_BODY: ${{ github.event.release.body }}
