name: Notify Discord on Release

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Release Notes to Discord
        uses: SethCohen/github-releases-to-discord@v1.16.2
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          color: "2105893"  # Optional: Customize the embed color
          username: "Release Bot"  # Optional: Customize the bot's username
          avatar_url: "https://e7.pngegg.com/pngimages/737/804/png-clipart-ultron-logo-marvel-comics-chitauri-hydra-ultron-face-fictional-characters.png"  # Optional: Customize the bot's avatar
          content: "@everyone"  # Optional: Mention everyone in the channel
          footer_title: "Release Notes"
          footer_icon_url: "https://e7.pngegg.com/pngimages/737/804/png-clipart-ultron-logo-marvel-comics-chitauri-hydra-ultron-face-fictional-characters.png"
          footer_timestamp: true
          max_description: '4096'
          reduce_headings: true
