name: Release Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build extension
        run: nix build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: stack-app-extension
          path: result/stack-app.zip

  release:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: stack-app-extension

      - name: Get version from manifest
        id: get_version
        run: |
          VERSION=$(unzip -p stack-app.zip manifest.json | jq -r .version)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: stack-app.zip
          tag_name: v${{ steps.get_version.outputs.version }}
          generate_release_notes: true 